version: '3.7'
services:
    db:
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
        secrets:
            - db_password
        volumes:
            - ./postgres/data:/var/lib/postgresql/data

    migrations:
        image: ${PHP_IMAGE:?PHP_IMAGE is not set or empty}
        command: >
            bash -c "while !</dev/tcp/db/5432; do sleep 1; done; php bin/console doctrine:migrations:migrate"

    php:
        image: ${PHP_IMAGE:?PHP_IMAGE is not set or empty}
        volumes:
            - ./php/conf/prod.ini:/usr/local/etc/php/conf.d/php.ini
            - ../public/upload:/srv/api/public/upload
            - ../var/log:/srv/api/var/log
        depends_on:
            - migrations

secrets:
   db_password:
     file: ./postgres/password.secret
