version: '3.7'
services:
    db:
        image: postgres:12
        environment:
            - POSTGRES_DB=${POSTGRES_DB:-symfony}
            - POSTGRES_USER=${POSTGRES_USER:-symfony}
        networks:
            - backend

    php:
        networks:
            - backend

    nginx:
        image: nginx:latest
        volumes:
            - ../public:/srv/api/public:rw,cached
            - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST:-localhost}
            LETSENCRYPT_HOST: ${VIRTUAL_HOST:-localhost}
        depends_on:
            - php
        networks:
            - backend
            - nginx-proxy

networks:
    backend:
        driver: bridge
    nginx-proxy:
        external:
            name: nginx-proxy
